version: '3.4'

services:
  rails:
    image: ruby:3.0
    user: "${UID:-1000}"
    working_dir: /myapp
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - ./backend:/myapp
      - bundler_cache:/usr/local/bundle
volumes:
  bundler_cache:
